

// Now populate them
var QUESTIONS = QUESTIONS || [
     {
        type: "nutrient",
        question: "Which nutrient is the main source of energy for your body?",
        options: ["Proteins", "Carbohydrates", "Fats", "Vitamins"],
        correct: 1,
        feedback: "Correct! Carbohydrates are your body's main fuel source, like gasoline for a car!",
        icon: "🍞"
    },
    {
        type: "nutrient",
        question: "Which nutrient helps build and repair muscles?",
        options: ["Carbohydrates", "Fats", "Proteins", "Water"],
        correct: 2,
        feedback: "Great job! Proteins are the building blocks for muscles and tissues.",
        icon: "🍗"
    },
    {
        type: "nutrient",
        question: "Which of these foods is rich in healthy fats?",
        options: ["White bread", "Soda", "Avocado", "Candy"],
        correct: 2,
        feedback: "Yes! Avocados have healthy fats that protect your organs.",
        icon: "🥑"
    },
    {
        type: "nutrient",
        question: "Which vitamin is important for good vision and is found in carrots?",
        options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B"],
        correct: 0,
        feedback: "Correct! Vitamin A in carrots helps you see well, especially at night!",
        icon: "🥕"
    },
    {
        type: "nutrient",
        question: "Which mineral helps build strong bones and teeth?",
        options: ["Iron", "Calcium", "Potassium", "Sodium"],
        correct: 1,
        feedback: "Yes! Calcium in milk and yogurt makes bones and teeth strong.",
        icon: "🥛"
    },
    {
        type: "nutrient",
        question: "Which nutrient helps your body absorb vitamins?",
        options: ["Carbohydrates", "Proteins", "Fats", "Fiber"],
        correct: 2,
        feedback: "Correct! Healthy fats help your body absorb important vitamins like A, D, E, and K!",
        icon: "🥑"
    },
    {
        type: "nutrient",
        question: "Which vitamin is made by your skin when you play outside in the sunshine?",
        options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
        correct: 2,
        feedback: "That's right! Your body makes Vitamin D from sunlight, which helps your bones grow strong.",
        icon: "☀️"
    },
    {
        type: "nutrient",
        question: "What nutrient in foods like oranges and strawberries helps heal cuts and fights germs?",
        options: ["Calcium", "Iron", "Vitamin C", "Protein"],
        correct: 2,
        feedback: "Correct! Vitamin C helps your body heal and keeps your immune system strong.",
        icon: "🍊"
    },
    {
        type: "nutrient",
        question: "Which mineral, found in foods like spinach and beans, helps carry oxygen in your blood?",
        options: ["Calcium", "Iron", "Potassium", "Zinc"],
        correct: 1,
        feedback: "Great job! Iron helps your blood carry oxygen to all parts of your body.",
        icon: "🩸"
    },
    {
        type: "nutrient",
        question: "What nutrient found in whole grains and vegetables helps with digestion?",
        options: ["Sugar", "Fiber", "Fat", "Protein"],
        correct: 1,
        feedback: "Yes! Fiber helps food move through your digestive system smoothly.",
        icon: "🌾"
    },
    {
        type: "nutrient",
        question: "Which nutrient provides the most energy per gram?",
        options: ["Carbohydrates", "Proteins", "Fats", "Vitamins"],
        correct: 2,
        feedback: "Correct! Fats provide the most concentrated energy, but we need them in smaller amounts.",
        icon: "⚡"
    },
    {
        type: "nutrient",
        question: "What is the main nutrient in foods like bread, pasta, and rice?",
        options: ["Protein", "Fat", "Carbohydrates", "Vitamins"],
        correct: 2,
        feedback: "That's right! These foods are rich in carbohydrates, which give you energy.",
        icon: "🍚"
    },
    {
        type: "nutrient",
        question: "Which vitamin helps your blood clot when you get a cut?",
        options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
        correct: 3,
        feedback: "Correct! Vitamin K helps your blood form clots to stop bleeding.",
        icon: "✋"
    },
    {
        type: "nutrient",
        question: "What nutrient is the main building block for your hair and nails?",
        options: ["Carbohydrates", "Fats", "Protein", "Fiber"],
        correct: 2,
        feedback: "Yes! Protein helps build and repair not just muscles, but also hair and nails.",
        icon: "💇"
    },
    {
        type: "nutrient",
        question: "Which mineral, found in bananas and potatoes, helps your muscles work properly?",
        options: ["Iron", "Calcium", "Potassium", "Sodium"],
        correct: 2,
        feedback: "Great! Potassium helps your muscles, including your heart, work correctly.",
        icon: "🍌"
    },
    {
        type: "nutrient",
        question: "What is the most important nutrient for staying hydrated?",
        options: ["Vitamins", "Water", "Minerals", "Carbohydrates"],
        correct: 1,
        feedback: "Correct! Water is essential for every cell in your body to work properly.",
        icon: "💧"
    },
    {
        type: "nutrient",
        question: "Which B vitamin helps your body turn food into energy?",
        options: ["Vitamin B6", "Vitamin B12", "All B vitamins", "Only Vitamin C"],
        correct: 2,
        feedback: "Yes! The B vitamin family works together to help convert food into fuel.",
        icon: "🔋"
    },
    {
        type: "nutrient",
        question: "What nutrient in dairy products helps your nerves send messages?",
        options: ["Calcium", "Protein", "Vitamin D", "Lactose"],
        correct: 0,
        feedback: "Correct! Calcium isn't just for bones—it also helps your nervous system function.",
        icon: "🧠"
    },
    {
        type: "nutrient",
        question: "Which nutrient acts like a shield against cell damage?",
        options: ["Antioxidants", "Fats", "Proteins", "Simple sugars"],
        correct: 0,
        feedback: "Right! Antioxidants in colorful fruits and vegetables protect your cells.",
        icon: "🛡️"
    },
    {
        type: "nutrient",
        question: "What nutrient in fish, like salmon, is especially good for brain health?",
        options: ["Omega-3 fats", "Vitamin C", "Calcium", "Fiber"],
        correct: 0,
        feedback: "Yes! Omega-3 fats in fish help your brain develop and function well.",
        icon: "🐟"
    },
    {
        type: "nutrient",
        question: "Which mineral is important for healthy teeth and helps prevent cavities?",
        options: ["Iron", "Fluoride", "Potassium", "Zinc"],
        correct: 1,
        feedback: "Correct! Fluoride strengthens tooth enamel and helps fight decay.",
        icon: "🦷"
    },
    {
        type: "nutrient",
        question: "What nutrient in beans and lentils gives you long-lasting energy?",
        options: ["Simple sugars", "Complex carbohydrates", "Saturated fats", "Water"],
        correct: 1,
        feedback: "Great! Complex carbs in beans break down slowly, giving you steady energy.",
        icon: "🫘"
    },
    {
        type: "nutrient",
        question: "Which vitamin helps you see well in the dark and is found in sweet potatoes?",
        options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin E"],
        correct: 0,
        feedback: "That's right! Vitamin A in orange vegetables helps with night vision.",
        icon: "🍠"
    },
    {
        type: "nutrient",
        question: "What nutrient in nuts and seeds helps your skin stay healthy?",
        options: ["Vitamin E", "Vitamin C", "Calcium", "Sodium"],
        correct: 0,
        feedback: "Correct! Vitamin E in nuts protects your skin cells.",
        icon: "🥜"
    },
    {
        type: "nutrient",
        question: "Which mineral, found in seafood and iodized salt, helps your thyroid gland?",
        options: ["Iron", "Iodine", "Calcium", "Magnesium"],
        correct: 1,
        feedback: "Yes! Iodine helps your thyroid gland control your metabolism.",
        icon: "🧂"
    },
    {
        type: "nutrient",
        question: "What nutrient do you get from sunlight that works with calcium for strong bones?",
        options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
        correct: 2,
        feedback: "Right! Vitamin D helps your body absorb and use calcium effectively.",
        icon: "🦴"
    },
    
    // Comparison questions
    {
        type: "comparison",
        question: "Which snack is healthier?",
        options: ["Apple with peanut butter", "Potato chips", "Chocolate bar", "Sugary cereal"],
        correct: 0,
        feedback: "Great choice! Apple with peanut butter gives you fiber, vitamins, and protein.",
        icon: "🍎"
    },
    {
        type: "comparison",
        question: "Which drink is the best choice for hydration?",
        options: ["Soda", "Fruit juice with added sugar", "Water", "Energy drink"],
        correct: 2,
        feedback: "Correct! Water hydrates your body without any added sugar.",
        icon: "💧"
    },
    {
        type: "comparison",
        question: "Which breakfast gives you lasting energy?",
        options: ["Donut", "Oatmeal with berries", "Sugary cereal", "Pastry"],
        correct: 1,
        feedback: "Yes! Oatmeal with berries has fiber and nutrients for lasting energy.",
        icon: "🥣"
    },
    {
        type: "comparison",
        question: "Which food is a better source of protein?",
        options: ["Fried chicken nuggets", "Grilled chicken breast", "Potato chips", "White bread"],
        correct: 1,
        feedback: "Great! Grilled chicken breast has more protein and less unhealthy fat than fried nuggets.",
        icon: "🍗"
    },
    
     {
        type: "comparison",
        question: "Which is a healthier dessert choice?",
        options: ["A bowl of fresh fruit salad", "A slice of chocolate cake", "A scoop of ice cream", "A candy bar"],
        correct: 0,
        feedback: "Great choice! Fresh fruit gives you vitamins, fiber, and natural sweetness.",
        icon: "🍓"
    },
    {
        type: "comparison",
        question: "Which sandwich filling is healthier?",
        options: ["Fried fish stick", "Grilled chicken breast", "Breaded chicken patty", "Hot dog"],
        correct: 1,
        feedback: "Yes! Grilled chicken breast has lean protein without unhealthy frying.",
        icon: "🥪"
    },
    {
        type: "comparison",
        question: "Which snack will give you more lasting energy?",
        options: ["A handful of gummy bears", "An apple with a handful of almonds", "A small bag of chips", "A chocolate cookie"],
        correct: 1,
        feedback: "Correct! The apple provides fiber and the almonds provide protein and healthy fats.",
        icon: "🍎"
    },
    {
        type: "comparison",
        question: "Which is a better breakfast drink?",
        options: ["A glass of orange juice", "A fruit smoothie with yogurt", "A can of soda", "A sugary chocolate milk"],
        correct: 1,
        feedback: "Good choice! A smoothie with yogurt has protein, vitamins, and less added sugar.",
        icon: "🥤"
    },
    {
        type: "comparison",
        question: "Which vegetable cooking method keeps more nutrients?",
        options: ["Boiling for a long time", "Steaming for a few minutes", "Frying in lots of oil", "Soaking in water"],
        correct: 1,
        feedback: "Right! Steaming vegetables quickly helps preserve their vitamins.",
        icon: "🥦"
    },
    {
        type: "comparison",
        question: "Which is a healthier after-school snack?",
        options: ["Celery sticks with hummus", "A bag of cheese puffs", "A frosted cupcake", "A handful of jelly beans"],
        correct: 0,
        feedback: "Excellent! Celery gives you fiber and hummus provides protein.",
        icon: "🥒"
    },
    {
        type: "comparison",
        question: "Which source of calcium is healthier?",
        options: ["A slice of processed cheese", "A glass of whole milk", "A cup of sugary yogurt", "A calcium-fortified candy"],
        correct: 1,
        feedback: "Yes! Plain milk provides calcium without unnecessary additives or sugar.",
        icon: "🥛"
    },
    {
        type: "comparison",
        question: "Which is a better lunch side dish?",
        options: ["Baked sweet potato fries", "Deep-fried French fries", "Onion rings", "Tater tots"],
        correct: 0,
        feedback: "Good thinking! Baked sweet potatoes have more vitamins and less unhealthy fat.",
        icon: "🍠"
    },
    {
        type: "comparison",
        question: "Which pizza topping is healthier?",
        options: ["Extra cheese and pepperoni", "Grilled chicken and vegetables", "Double bacon", "Extra sausage"],
        correct: 1,
        feedback: "Correct! Chicken and veggies add protein and nutrients without too much saturated fat.",
        icon: "🍕"
    },
    {
        type: "comparison",
        question: "Which is a better treat on a hot day?",
        options: ["A fruit popsicle with real fruit", "A milkshake with whipped cream", "A slushie with lots of syrup", "An ice cream sundae with toppings"],
        correct: 0,
        feedback: "Great choice! A fruit popsicle can be refreshing with natural fruit sugars.",
        icon: "🍧"
    },
    {
        type: "comparison",
        question: "Which bread is healthier for a sandwich?",
        options: ["White bread", "Whole wheat bread", "Sweet Hawaiian rolls", "Buttery croissant"],
        correct: 1,
        feedback: "Yes! Whole wheat bread has more fiber and nutrients than refined white bread.",
        icon: "🍞"
    },
    {
        type: "comparison",
        question: "Which is a healthier protein for your taco?",
        options: ["Crispy fried fish", "Seasoned ground beef", "Grilled shrimp", "Breaded chicken strips"],
        correct: 2,
        feedback: "Good choice! Grilled shrimp is lean protein with healthy omega-3s.",
        icon: "🦐"
    },
    {
        type: "comparison",
        question: "Which salad is more nutritious?",
        options: ["Iceberg lettuce with ranch dressing", "Spinach with tomatoes, carrots, and vinaigrette", "Just plain lettuce", "A salad with lots of croutons and bacon bits"],
        correct: 1,
        feedback: "Excellent! Dark leafy greens and colorful veggies provide many more vitamins.",
        icon: "🥗"
    },
    {
        type: "comparison",
        question: "Which is a better choice for strong bones?",
        options: ["A calcium supplement candy", "A glass of fortified orange juice", "A cup of yogurt", "A piece of white bread"],
        correct: 2,
        feedback: "Yes! Yogurt provides calcium along with protein and probiotics.",
        icon: "🦴"
    },
    {
        type: "comparison",
        question: "Which cereal is a healthier start to the day?",
        options: ["A cereal with a cartoon character and marshmallows", "Oatmeal with nuts and berries", "A sugary frosted cereal", "A cereal that's mostly puffed rice and sugar"],
        correct: 1,
        feedback: "Great! Oatmeal with nuts and berries provides fiber, protein, and vitamins.",
        icon: "🥣"
    },
    {
        type: "comparison",
        question: "Which is a better after-sport recovery snack?",
        options: ["A sports drink with sugar", "Chocolate bar", "Banana with a glass of water", "A bag of pretzels"],
        correct: 2,
        feedback: "Correct! The banana provides potassium and carbs, and water rehydrates you.",
        icon: "🍌"
    },
    {
        type: "comparison",
        question: "Which pasta dish is healthier?",
        options: ["Creamy Alfredo pasta", "Spaghetti with tomato sauce and vegetables", "Macaroni and cheese", "Pasta with butter and salt"],
        correct: 1,
        feedback: "Yes! Tomato sauce and veggies add vitamins and fiber without heavy cream.",
        icon: "🍝"
    },
    {
        type: "comparison",
        question: "Which is a healthier way to flavor your food?",
        options: ["Sprinkling with lots of salt", "Adding herbs and spices", "Pouring on sugary ketchup", "Using lots of butter"],
        correct: 1,
        feedback: "Great! Herbs and spices add flavor without extra sodium, sugar, or fat.",
        icon: "🌿"
    },
    {
        type: "comparison",
        question: "Which is a better source of vitamin C?",
        options: ["A vitamin C gummy with added sugar", "A fresh red bell pepper", "A glass of lemonade", "A piece of white bread"],
        correct: 1,
        feedback: "Correct! Red bell peppers actually have more vitamin C than oranges!",
        icon: "🫑"
    },
    {
        type: "comparison",
        question: "Which is a healthier choice at a barbecue?",
        options: ["A greasy cheeseburger", "A grilled chicken breast", "A hot dog with chili", "Ribs with sugary sauce"],
        correct: 1,
        feedback: "Good choice! Grilled chicken is lean protein without as much saturated fat.",
        icon: "🍗"
    },
    // True/False questions
    {
        type: "truefalse",
        question: "True or False: Eating a variety of colorful fruits and vegetables is important for health.",
        options: ["True", "False"],
        correct: 0,
        feedback: "Correct! Different colors mean different nutrients - eat the rainbow!",
        icon: "🌈"
    },
    {
        type: "truefalse",
        question: "True or False: You should only eat foods you like and avoid trying new healthy foods.",
        options: ["True", "False"],
        correct: 1,
        feedback: "Actually false! Trying new healthy foods helps you get all the nutrients you need.",
        icon: "🍽️"
    },
    {
        type: "truefalse",
        question: "True or False: Exercise is important for a healthy body and mind.",
        options: ["True", "False"],
        correct: 0,
        feedback: "Yes! Exercise keeps your body strong and your mind happy.",
        icon: "🏃"
    },
    {
        type: "truefalse",
        question: "True or False: All fats are bad for your health.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Healthy fats from nuts, avocados, and fish are good for your body.",
        icon: "🥑"
    },
     {
        type: "truefalse",
        question: "True or False: Drinking water is the best way to quench your thirst.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Water hydrates your body perfectly without any sugar or additives.",
        icon: "💧"
    },
    {
        type: "truefalse",
        question: "True or False: Eating breakfast helps you concentrate better at school.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! A good breakfast fuels your brain for learning and focusing.",
        icon: "🍳"
    },
    {
        type: "truefalse",
        question: "True or False: All snacks are bad for you.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Healthy snacks like fruits, veggies, and nuts are great for energy.",
        icon: "🍏"
    },
    {
        type: "truefalse",
        question: "True or False: Your body needs some fat to stay healthy.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Healthy fats from nuts, avocados, and fish are essential for your body.",
        icon: "🥑"
    },
    {
        type: "truefalse",
        question: "True or False: Brown eggs are more nutritious than white eggs.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! The color of the eggshell doesn't affect nutrition—both are equally healthy!",
        icon: "🥚"
    },
    {
        type: "truefalse",
        question: "True or False: You should wash your hands before preparing or eating food.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Washing hands removes germs that could make you sick.",
        icon: "🧼"
    },
    {
        type: "truefalse",
        question: "True or False: Frozen fruits and vegetables are less nutritious than fresh ones.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Frozen produce is often flash-frozen at peak freshness, keeping nutrients locked in!",
        icon: "❄️"
    },
    {
        type: "truefalse",
        question: "True or False: Eating slowly helps your digestion.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Eating slowly gives your body time to digest and helps you recognize when you're full.",
        icon: "🐌"
    },
    {
        type: "truefalse",
        question: "True or False: You need to drink milk to have strong bones.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! While milk is a great source, you can also get calcium from leafy greens, fortified foods, and some fish.",
        icon: "🦴"
    },
    {
        type: "truefalse",
        question: "True or False: Sugar gives you quick energy that lasts for hours.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Sugar gives a quick energy spike, but it crashes quickly. Complex carbs give longer-lasting energy.",
        icon: "📉"
    },
    {
        type: "truefalse",
        question: "True or False: Eating a rainbow of colorful foods is good for your health.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Different colors often mean different vitamins and antioxidants.",
        icon: "🌈"
    },
    {
        type: "truefalse",
        question: "True or False: It's okay to skip meals if you're not hungry.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Regular meals help keep your energy steady and provide consistent nutrients.",
        icon: "⏰"
    },
    {
        type: "truefalse",
        question: "True or False: Nuts are a healthy snack even though they contain fat.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Nuts contain healthy fats, protein, and fiber—great in moderation!",
        icon: "🥜"
    },
    {
        type: "truefalse",
        question: "True or False: All bacteria in food are harmful.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Some bacteria, like probiotics in yogurt, are actually good for your gut!",
        icon: "🦠"
    },
    {
        type: "truefalse",
        question: "True or False: Fruit juice is just as healthy as eating whole fruit.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Whole fruit has fiber that juice often lacks, and juice can have concentrated sugar.",
        icon: "🍎"
    },
    {
        type: "truefalse",
        question: "True or False: It's important to read food labels to know what you're eating.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Labels tell you about ingredients, sugar, salt, and nutrients.",
        icon: "🏷️"
    },
    {
        type: "truefalse",
        question: "True or False: Cooking vegetables always destroys their vitamins.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! While some cooking methods can reduce nutrients, others can make some vitamins easier to absorb!",
        icon: "🥦"
    },
    {
        type: "truefalse",
        question: "True or False: You should drink 8 glasses of water every day.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! This is a good general goal, but needs vary with activity and weather.",
        icon: "8️⃣"
    },
    {
        type: "truefalse",
        question: "True or False: White meat chicken is healthier than dark meat.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Both are healthy! Dark meat has slightly more iron and zinc, while white meat is leaner.",
        icon: "🍗"
    },
    {
        type: "truefalse",
        question: "True or False: Eating fish makes your brain smarter.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! The omega-3 fats in fish support brain development and function!",
        icon: "🐟"
    },
    
    // Balanced diet questions
    {
        type: "balanced",
        question: "What does a balanced diet include?",
        options: ["Only fruits", "Foods from all food groups", "Only protein", "Lots of sweets"],
        correct: 1,
        feedback: "Correct! A balanced diet includes fruits, vegetables, grains, protein, and dairy.",
        icon: "⚖️"
    },
    {
        type: "balanced",
        question: "How much of your plate should be fruits and vegetables?",
        options: ["One quarter", "One third", "Half", "Just a little"],
        correct: 2,
        feedback: "Yes! Half your plate should be fruits and vegetables for good health.",
        icon: "🍽️"
    },
    {
        type: "balanced",
        question: "Which food group should make up the smallest part of your plate?",
        options: ["Fruits and vegetables", "Grains", "Protein", "Fats and sweets"],
        correct: 3,
        feedback: "Correct! Fats and sweets should be eaten in small amounts.",
        icon: "🍰"
    },
    
    // Exercise questions
    {
        type: "exercise",
        question: "Why is exercise important for health?",
        options: ["Makes muscles strong", "Keeps heart healthy", "Makes you feel happy", "All of the above"],
        correct: 3,
        feedback: "Correct! Exercise does all of these things and more!",
        icon: "❤️"
    },
    {
        type: "exercise",
        question: "How much physical activity should kids get each day?",
        options: ["15 minutes", "30 minutes", "60 minutes", "2 hours"],
        correct: 2,
        feedback: "Yes! Kids should aim for at least 60 minutes of physical activity daily.",
        icon: "⏱️"
    },
    {
        type: "exercise",
        question: "Which is NOT a good form of exercise?",
        options: ["Playing soccer", "Riding a bike", "Watching TV", "Swimming"],
        correct: 2,
        feedback: "Right! Watching TV is not exercise. Get moving instead!",
        icon: "📺"
    },
     {
        type: "balanced",
        question: "Which food group should fill about a quarter of your plate?",
        options: ["Fruits", "Vegetables", "Grains", "Protein"],
        correct: 3,
        feedback: "Correct! Protein foods like meat, beans, or tofu should fill about one quarter of your plate.",
        icon: "🍽️"
    },
    {
        type: "balanced",
        question: "What does 'eating a rainbow' mean?",
        options: ["Eating colorful candies", "Eating fruits and vegetables of different colors", "Eating only red foods", "Eating foods with food coloring"],
        correct: 1,
        feedback: "Yes! Different colored fruits and vegetables provide different vitamins and minerals.",
        icon: "🌈"
    },
    {
        type: "balanced",
        question: "Which of these is NOT one of the five main food groups?",
        options: ["Fruits", "Vegetables", "Sugary drinks", "Dairy"],
        correct: 2,
        feedback: "Right! Sugary drinks aren't a food group and should be limited.",
        icon: "🚫"
    },
    {
        type: "balanced",
        question: "How many servings of vegetables should kids eat each day?",
        options: ["1-2", "2-3", "3-4", "4-5 or more"],
        correct: 3,
        feedback: "Correct! Kids should aim for 4-5 servings of vegetables daily for optimal health.",
        icon: "🥦"
    },
    {
        type: "balanced",
        question: "What should you include in a balanced lunch?",
        options: ["Only carbohydrates", "Protein, grains, and vegetables", "Just protein", "Only foods you like"],
        correct: 1,
        feedback: "Great! A balanced lunch includes multiple food groups for sustained energy.",
        icon: "🥪"
    },
    {
        type: "balanced",
        question: "Which of these is a healthy protein choice for a balanced diet?",
        options: ["Beans and lentils", "Bacon every day", "Fried chicken nuggets", "Hot dogs"],
        correct: 0,
        feedback: "Yes! Beans and lentils are excellent plant-based protein sources.",
        icon: "🫘"
    },
    {
        type: "balanced",
        question: "What percentage of your grains should be whole grains?",
        options: ["At least half", "None", "Only a quarter", "All of them"],
        correct: 0,
        feedback: "Correct! At least half your grains should be whole grains like brown rice or whole wheat bread.",
        icon: "🌾"
    },
    {
        type: "balanced",
        question: "Why is variety important in a balanced diet?",
        options: ["It's more fun", "It ensures you get all different nutrients", "It's cheaper", "It's less work"],
        correct: 1,
        feedback: "Right! Different foods provide different nutrients your body needs.",
        icon: "🎯"
    },
    {
        type: "balanced",
        question: "Which of these is a healthy dairy or dairy alternative?",
        options: ["Sugar-free yogurt", "Ice cream sundae", "Whipped cream", "Cheese puffs"],
        correct: 0,
        feedback: "Yes! Plain or sugar-free yogurt provides calcium and protein without too much added sugar.",
        icon: "🥛"
    },
    {
        type: "balanced",
        question: "What should you do if you don't like a certain vegetable?",
        options: ["Never eat it again", "Try it prepared a different way", "Only eat fruits instead", "Give up on all vegetables"],
        correct: 1,
        feedback: "Good thinking! Cooking or seasoning it differently might make it taste better to you.",
        icon: "👨‍🍳"
    },
    {
        type: "balanced",
        question: "How can you make sure you're eating balanced meals at school?",
        options: ["Choose only pizza", "Pack a lunch with different food groups", "Skip lunch", "Trade all your vegetables for dessert"],
        correct: 1,
        feedback: "Excellent! Packing a lunch lets you control what food groups you include.",
        icon: "🎒"
    },
    {
        type: "balanced",
        question: "Which meal is most important for a balanced diet?",
        options: ["Breakfast", "Lunch", "Dinner", "All meals are important"],
        correct: 3,
        feedback: "Correct! All meals contribute to your overall daily nutrition.",
        icon: "🍽️"
    },
    {
        type: "balanced",
        question: "What does 'portion size' mean?",
        options: ["The size of your plate", "How much food you choose to eat at one time", "The weight of the food", "The cost of the food"],
        correct: 1,
        feedback: "Yes! Portion size is the amount of food you eat at one sitting.",
        icon: "📏"
    },
    {
        type: "balanced",
        question: "Which of these is a balanced snack?",
        options: ["Apple slices with peanut butter", "A bag of chips", "A candy bar", "A can of soda"],
        correct: 0,
        feedback: "Great choice! The apple provides fiber and vitamins, while peanut butter adds protein.",
        icon: "🍎"
    },
    {
        type: "balanced",
        question: "Why should you limit added sugars in your diet?",
        options: ["They provide no nutrients", "They can lead to energy crashes", "They can harm your teeth", "All of the above"],
        correct: 3,
        feedback: "Correct! Added sugars have many negative effects and should be eaten in small amounts.",
        icon: "🍬"
    },
    {
        type: "balanced",
        question: "What does a balanced dinner plate look like?",
        options: ["Mostly meat with a little vegetable", "Half vegetables, quarter protein, quarter grains", "All grains", "Mostly dessert with a little dinner"],
        correct: 1,
        feedback: "Yes! The ideal plate has half vegetables, a quarter protein, and a quarter grains.",
        icon: "🍽️"
    },
    {
        type: "balanced",
        question: "How often should you eat fish in a balanced diet?",
        options: ["Never", "Once a week", "Every day", "Only on special occasions"],
        correct: 1,
        feedback: "Right! Eating fish about once a week provides healthy omega-3 fats.",
        icon: "🐟"
    },
    {
        type: "balanced",
        question: "What should you drink most often with your meals?",
        options: ["Water or milk", "Soda", "Sweet tea", "Fruit punch"],
        correct: 0,
        feedback: "Correct! Water and milk are the healthiest beverage choices with meals.",
        icon: "💧"
    },
    {
        type: "balanced",
        question: "Which of these is a whole grain?",
        options: ["White bread", "White rice", "Oatmeal", "Pretzels"],
        correct: 2,
        feedback: "Yes! Oatmeal is a whole grain that hasn't had its nutritious parts removed.",
        icon: "🌾"
    },
    {
        type: "balanced",
        question: "Why is it important to eat foods from all food groups?",
        options: ["No single food has all the nutrients you need", "It's more expensive", "It takes more time", "It's a rule without reason"],
        correct: 0,
        feedback: "Exactly! Your body needs over 40 different nutrients that come from various foods.",
        icon: "🧩"
    },

    {
        type: "exercise",
        question: "What is one benefit of regular exercise?",
        options: ["Stronger muscles", "Better sleep", "Improved mood", "All of the above"],
        correct: 3,
        feedback: "Correct! Exercise has all these benefits and many more!",
        icon: "💪"
    },
    {
        type: "exercise",
        question: "Which activity counts as aerobic exercise?",
        options: ["Playing video games", "Reading a book", "Swimming laps", "Watching TV"],
        correct: 2,
        feedback: "Yes! Swimming is a great aerobic exercise that gets your heart pumping.",
        icon: "🏊"
    },
    {
        type: "exercise",
        question: "How can you make exercise more fun?",
        options: ["Do it with friends", "Listen to music", "Try different activities", "All of the above"],
        correct: 3,
        feedback: "Great ideas! Making exercise fun helps you stick with it.",
        icon: "😄"
    },
    {
        type: "exercise",
        question: "What should you do before starting vigorous exercise?",
        options: ["Eat a big meal", "Warm up your muscles", "Drink a soda", "Skip it and start fast"],
        correct: 1,
        feedback: "Correct! Warming up helps prevent injuries and prepares your body.",
        icon: "🔥"
    },
    {
        type: "exercise",
        question: "Which of these is a strength-building exercise?",
        options: ["Playing tag", "Riding a bike", "Climbing on playground equipment", "All of the above"],
        correct: 3,
        feedback: "Yes! Many fun activities help build strength, especially climbing!",
        icon: "🧗"
    },
    {
        type: "exercise",
        question: "How does exercise help your brain?",
        options: ["It doesn't", "It increases blood flow to the brain", "It makes you tired", "It only helps your body"],
        correct: 1,
        feedback: "Right! Exercise sends more oxygen-rich blood to your brain, helping you think better.",
        icon: "🧠"
    },
    {
        type: "exercise",
        question: "What should you drink during and after exercise?",
        options: ["Water", "Energy drinks", "Soda", "Milkshake"],
        correct: 0,
        feedback: "Correct! Water is best for replacing fluids lost through sweat.",
        icon: "💧"
    },
    {
        type: "exercise",
        question: "Which activity helps improve flexibility?",
        options: ["Stretching", "Sitting still", "Playing chess", "Eating snacks"],
        correct: 0,
        feedback: "Yes! Gentle stretching helps keep your muscles and joints flexible.",
        icon: "🤸"
    },
    {
        type: "exercise",
        question: "How can you get more exercise during the school day?",
        options: ["Take the stairs", "Walk or bike to school", "Play actively at recess", "All of the above"],
        correct: 3,
        feedback: "Excellent! Small choices add up to more daily activity.",
        icon: "🏫"
    },
    {
        type: "exercise",
        question: "What is 'moderate' exercise?",
        options: ["Exercise that makes you breathe harder but you can still talk", "Exercise where you can sing easily", "Not moving at all", "Only professional sports"],
        correct: 0,
        feedback: "Right! Moderate exercise raises your heart rate but you can still hold a conversation.",
        icon: "💬"
    },
    {
        type: "exercise",
        question: "Why is rest important in an exercise routine?",
        options: ["It gives your muscles time to repair", "You get bored of exercise", "Rest is not important", "To watch more TV"],
        correct: 0,
        feedback: "Correct! Rest days allow your muscles to recover and grow stronger.",
        icon: "😴"
    },
    {
        type: "exercise",
        question: "Which of these is a weight-bearing exercise good for bones?",
        options: ["Swimming", "Jumping rope", "Biking", "Playing cards"],
        correct: 1,
        feedback: "Yes! Jumping rope puts healthy stress on bones, making them stronger.",
        icon: "🦴"
    },
    {
        type: "exercise",
        question: "How does exercise help your heart?",
        options: ["Makes it beat faster sometimes", "Strengthens the heart muscle", "Doesn't help at all", "Only helps if you're an athlete"],
        correct: 1,
        feedback: "Right! Regular exercise makes your heart stronger and more efficient.",
        icon: "❤️"
    },
    {
        type: "exercise",
        question: "What should you wear for safe exercise?",
        options: ["Proper shoes", "Comfortable clothes", "Weather-appropriate gear", "All of the above"],
        correct: 3,
        feedback: "Good thinking! The right gear helps prevent injuries and keeps you comfortable.",
        icon: "👟"
    },
    {
        type: "exercise",
        question: "Which family activity provides exercise?",
        options: ["Going for a hike together", "Watching a movie", "Playing board games", "Eating out"],
        correct: 0,
        feedback: "Yes! Active family time is fun and healthy for everyone.",
        icon: "👨‍👩‍👧‍👦"
    },
    {
        type: "exercise",
        question: "How long should you wait to swim after eating?",
        options: ["30 minutes to 1 hour", "5 minutes", "3 hours", "You can swim immediately"],
        correct: 0,
        feedback: "Correct! Waiting a bit helps prevent cramps while swimming.",
        icon: "⏱️"
    },
    {
        type: "exercise",
        question: "What is the best time of day to exercise?",
        options: ["Whenever you can fit it in consistently", "Only in the morning", "Only in the evening", "Never"],
        correct: 0,
        feedback: "Right! Consistency matters more than the specific time of day.",
        icon: "⏰"
    },
    {
        type: "exercise",
        question: "How can exercise help with stress?",
        options: ["It releases feel-good chemicals in your brain", "It makes you more stressed", "It doesn't help", "It only helps adults"],
        correct: 0,
        feedback: "Yes! Exercise releases endorphins that can improve your mood.",
        icon: "😊"
    },
    {
        type: "exercise",
        question: "Which of these counts as exercise?",
        options: ["Dancing to your favorite songs", "Walking the dog", "Helping with yard work", "All of the above"],
        correct: 3,
        feedback: "Correct! Many everyday activities count as exercise if they get you moving!",
        icon: "🕺"
    },
    {
        type: "exercise",
        question: "Why is it important to cool down after exercise?",
        options: ["It helps your heart rate return to normal gradually", "It's not important", "To have a snack", "To immediately sit down"],
        correct: 0,
        feedback: "Right! Cooling down helps prevent dizziness and muscle stiffness.",
        icon: "🧊"
    },
    
    // Eating disorder awareness (age-appropriate)
    {
        type: "awareness",
        question: "If a friend is always worried about their weight and avoids eating, what should you do?",
        options: ["Make fun of them", "Tell a trusted adult", "Ignore them", "Give them candy"],
        correct: 1,
        feedback: "Good! Telling a trusted adult can help your friend get support.",
        icon: "🤝"
    },
    {
        type: "awareness",
        question: "True or False: Everyone's body is different and that's okay.",
        options: ["True", "False"],
        correct: 0,
        feedback: "Yes! Bodies come in all shapes and sizes, and all are valuable.",
        icon: "👫"
    },
    {
        type: "awareness",
        question: "Who should you talk to if you're worried about your eating habits?",
        options: ["No one", "A trusted adult", "Only friends", "Social media"],
        correct: 1,
        feedback: "Correct! Talking to a trusted adult like a parent or teacher can help.",
        icon: "🗣️"
    },
     {
        type: "awareness",
        question: "What should you do if a friend often skips lunch to 'be thin'?",
        options: ["Tell them they're right to skip meals", "Talk to a trusted adult about your concern", "Ignore it", "Start skipping meals too"],
        correct: 1,
        feedback: "Good choice! A trusted adult can help your friend get the support they need.",
        icon: "🤝"
    },
    {
        type: "awareness",
        question: "True or False: It's normal for bodies to grow at different rates.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Everyone grows and develops at their own unique pace.",
        icon: "📈"
    },
    {
        type: "awareness",
        question: "What is a healthy attitude toward food?",
        options: ["Viewing food as fuel for your body", "Thinking of foods as 'good' or 'bad'", "Feeling guilty after eating", "Only eating when you're extremely hungry"],
        correct: 0,
        feedback: "Yes! Food is nourishment that helps your body grow, learn, and play.",
        icon: "⛽"
    },
    {
        type: "awareness",
        question: "If you see mean comments about someone's weight online, what should you do?",
        options: ["Like the comments", "Share them with others", "Report the comments and offer support", "Add your own mean comment"],
        correct: 2,
        feedback: "Correct! Standing up against bullying and offering kindness helps everyone.",
        icon: "📱"
    },
    {
        type: "awareness",
        question: "True or False: Your worth is determined by your weight or appearance.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Your value comes from who you are, not how you look.",
        icon: "❤️"
    },
    {
        type: "awareness",
        question: "What should you do if you feel pressure to look a certain way?",
        options: ["Talk to a parent or trusted adult", "Try to change your body dramatically", "Stop eating", "Hide your feelings"],
        correct: 0,
        feedback: "Good thinking! Talking helps you process these feelings in a healthy way.",
        icon: "🗣️"
    },
    {
        type: "awareness",
        question: "Why is it harmful to make jokes about someone's weight?",
        options: ["It can hurt their feelings deeply", "It might lead to unhealthy habits", "It creates a negative environment", "All of the above"],
        correct: 3,
        feedback: "Correct! Weight jokes can have serious emotional consequences.",
        icon: "🚫"
    },
    {
        type: "awareness",
        question: "True or False: Dieting or restricting food is safe for kids to try on their own.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Kids should never diet without a doctor's guidance, as it can interfere with growth.",
        icon: "⚠️"
    },
    {
        type: "awareness",
        question: "What is body positivity?",
        options: ["Loving how your body looks all the time", "Appreciating what your body can DO", "Wanting to change everything", "Comparing your body to others"],
        correct: 1,
        feedback: "Yes! It's about respecting and being grateful for your body's abilities.",
        icon: "👍"
    },
    {
        type: "awareness",
        question: "If an advertisement makes you feel bad about your body, what should you remember?",
        options: ["Ads often show unrealistic images", "My body is fine as it is", "I don't need to look like models", "All of the above"],
        correct: 3,
        feedback: "Correct! Keep these positive thoughts in mind when you see unrealistic ads.",
        icon: "📺"
    },
    {
        type: "awareness",
        question: "True or False: It's okay to eat more on some days and less on others.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Appetite naturally varies with activity, growth spurts, and other factors.",
        icon: "📊"
    },
    {
        type: "awareness",
        question: "Who can help if you're worried about a friend's eating habits?",
        options: ["School counselor", "Parent or teacher", "Coach", "Any trusted adult"],
        correct: 3,
        feedback: "Yes! Any trusted adult can help connect your friend with appropriate support.",
        icon: "👨‍🏫"
    },
    {
        type: "awareness",
        question: "What does 'healthy' mean for your body?",
        options: ["Having lots of energy", "Being able to play and learn", "Feeling strong", "All of the above"],
        correct: 3,
        feedback: "Correct! Health is about how you feel and function, not just appearance.",
        icon: "💪"
    },
    {
        type: "awareness",
        question: "True or False: You should compare your body to your friends' bodies.",
        options: ["True", "False"],
        correct: 1,
        feedback: "False! Every body is unique and develops differently.",
        icon: "👥"
    },
    {
        type: "awareness",
        question: "What is a sign that someone might need help with food issues?",
        options: ["They suddenly avoid eating with others", "They talk constantly about calories", "They exercise excessively to 'burn off' food", "All of the above"],
        correct: 3,
        feedback: "Yes! These can be signs that someone is struggling.",
        icon: "🚩"
    },
    {
        type: "awareness",
        question: "How can you support a friend who's being teased about their size?",
        options: ["Stand up for them", "Sit with them at lunch", "Tell them they're great as they are", "All of the above"],
        correct: 3,
        feedback: "Excellent! All these actions show kindness and support.",
        icon: "🤗"
    },
    {
        type: "awareness",
        question: "True or False: Boys can have eating disorders too.",
        options: ["True", "False"],
        correct: 0,
        feedback: "True! Eating disorders can affect anyone, regardless of gender.",
        icon: "👦"
    },
    {
        type: "awareness",
        question: "What should you do if you're unhappy with your body?",
        options: ["Focus on what your body can do", "Talk to a parent about your feelings", "Practice gratitude for your health", "All of the above"],
        correct: 3,
        feedback: "Good strategies! These positive steps are healthier than criticism.",
        icon: "💭"
    },
    {
        type: "awareness",
        question: "Why is it important to respect all body types?",
        options: ["Because everyone deserves respect", "Different bodies are normal", "You don't know someone's health story", "All of the above"],
        correct: 3,
        feedback: "Correct! There are many good reasons to respect all bodies.",
        icon: "🙏"
    },
    {
        type: "awareness",
        question: "What is the best source of health advice for your specific body?",
        options: ["Social media influencers", "A doctor or dietitian", "Friends at school", "Magazine articles"],
        correct: 1,
        feedback: "Yes! Healthcare professionals give personalized, safe advice.",
        icon: "🩺"
    }
];

var FACTS = FACTS || [
    "Did you know? Drinking water helps your brain work better!",
    "Fun fact: Carrots were originally purple, not orange!",
    "Eating a rainbow of fruits and vegetables gives you different nutrients!",
    "Exercise releases 'feel-good' chemicals in your brain called endorphins!",
    "Protein isn't just in meat - beans, nuts, and tofu are great sources too!",
    "Calcium in dairy products helps build strong bones while you're growing!",
    "Fiber in whole grains helps you feel full and keeps your digestive system healthy!",
    "Bananas are a great source of potassium, which helps your muscles work!",
    "Tomatoes are actually fruits, not vegetables!",
    "Strawberries have more vitamin C than oranges!",
    "Drinking milk helps you get vitamin D for strong bones!",
    "Eating breakfast helps you concentrate better in school!",
    "Watermelon is 92% water - great for hydration!",
    "Broccoli has more protein than most other vegetables!",
    "Sleep is just as important as diet and exercise for good health!",
     "Apples float in water because they are 25% air!",
    "Your brain is about 75% water, so staying hydrated helps you think!",
    "Cucumbers are 96% water - almost as much as a glass of water!",
    "Spinach is packed with iron, which helps carry oxygen in your blood!",
    "Sweet potatoes are one of the most nutritious vegetables on Earth!",
    "Almonds are actually seeds, not nuts!",
    "Peanuts grow underground, not on trees!",
    "Honey never spoils - archaeologists found edible honey in ancient Egyptian tombs!",
    "Kiwi fruits have more vitamin C than oranges!",
    "Pineapples contain an enzyme that can break down proteins - that's why they can make your mouth tingle!",
    "Your body has about 60,000 miles of blood vessels - eating healthy keeps them strong!",
    "Your heart beats about 100,000 times a day - exercise makes it stronger!",
    "Kids need about 60 minutes of physical activity every day!",
    "Stretching helps your muscles stay flexible and prevents injuries!",
    "Yogurt contains good bacteria that help your digestive system!",
    "Oats can help lower cholesterol, even though that's more important for adults!",
    "Avocados are actually berries!",
    "Bell peppers come in different colors because they ripen at different stages!",
    "Eating carrots won't actually give you super night vision, but they do help your eyes!",
    "Blueberries are called 'brain berries' because they're good for your brain!",
    "Walnuts look like tiny brains and are great for brain health!",
    "Kidney beans get their name because they look like human kidneys!",
    "Cacao beans, which make chocolate, contain antioxidants that are good for your heart!",
    "Dark chocolate has more antioxidants than milk chocolate!",
    "Your taste buds are replaced every 10-14 days!",
    "Exercise helps you sleep better at night!",
    "Laughing for 15 minutes burns about 10-40 calories!",
    "Jumping rope is one of the best exercises for your heart and bones!",
    "Dancing is a fun way to exercise your whole body!",
    "Swimming uses almost all your muscle groups at once!",
    "Your bones are constantly rebuilding themselves - that's why calcium is so important!",
    "Vitamin C helps your body heal cuts and wounds faster!",
    "Oranges are not the best source of vitamin C - red bell peppers have more!",
    "Broccoli and cauliflower are actually flowers!",
    "There are over 7,500 different kinds of apples in the world!",
    "Eating a variety of foods is like giving your body a toolbox with all the right tools!",
    "Eggs are one of the few foods that naturally contain vitamin D!",
    "Salmon contains omega-3 fats that are great for brain development!",
    "Sunflower seeds are packed with vitamin E, which protects your cells!",
    "Lentils are one of the oldest known foods - people have eaten them for 13,000 years!",
    "Quinoa is pronounced 'keen-wah' and is a complete protein!",
    "Brown rice has more fiber and nutrients than white rice!",
    "Whole wheat bread has more vitamins than white bread!",
    "Your body is made up of trillions of cells that need different nutrients to work properly!",
    "Drinking cold water can actually help burn a few extra calories as your body warms it up!",
    "Cinnamon comes from the bark of trees!",
    "Garlic is actually part of the onion family!",
    "Onions make you cry because they release a gas when you cut them!",
    "Potatoes were the first vegetable grown in space!",
    "Tomatoes were once called 'love apples'!",
    "Eating spicy food can boost your metabolism a little bit!",
    "Turkey contains tryptophan, which can make you feel sleepy!",
    "Pumpkins are 90% water!",
    "Eating the skin of fruits and vegetables gives you extra fiber!",
    "Celery is mostly water and fiber, so it takes more energy to digest than it contains!",
    "Raspberries are not actually berries - they're aggregate fruits!",
    "Strawberries are the only fruit with seeds on the outside!",
    "Bananas are berries, but strawberries aren't!",
    "Figs are actually inverted flowers!",
    "Pomegranates can have up to 600 seeds inside!",
    "Your body needs fat to absorb some vitamins like A, D, E, and K!",
    "Olive oil is a healthy fat that's good for your heart!",
    "Nuts are some of the most nutrient-dense foods on the planet!",
    "Brazil nuts are the best source of selenium, which helps your immune system!",
    "Mushrooms are the only non-animal source of vitamin D!",
    "Kale is one of the most nutrient-rich vegetables!",
    "Beets can turn your urine pink - it's harmless and just shows the pigments are passing through!",
    "Asparagus can make your urine smell funny - it's completely normal!",
    "Your small intestine is about 22 feet long - that's longer than a giraffe is tall!",
    "Your stomach acid is strong enough to dissolve metal!",
    "You produce about 1-2 liters of saliva every day to help digest food!",
    "Chewing your food well helps your body absorb nutrients better!",
    "Eating slowly gives your brain time to realize you're full!",
    "It takes about 20 minutes for your brain to get the 'I'm full' signal!",
    "Drinking water before meals can help you eat just the right amount!",
    "Foods with bright colors usually have more nutrients!",
    "Purple foods like blueberries and purple cabbage contain special antioxidants!",
    "Orange foods like carrots and sweet potatoes are great for eye health!",
    "Green leafy vegetables are packed with vitamins and minerals!",
    "Red foods like tomatoes and watermelon contain lycopene, which is good for your heart!",
    "White foods like garlic and onions have special compounds that fight germs!",
    "Eating a protein-rich breakfast can help you feel full longer!",
    "Greek yogurt has more protein than regular yogurt!",
    "Cottage cheese is packed with protein and calcium!",
    "Tofu is made from soybeans and is a great plant-based protein!",
    "Chia seeds can absorb 10 times their weight in water!",
    "Flax seeds are one of the best plant sources of omega-3 fats!",
    "Pumpkin seeds are packed with magnesium, which helps your muscles relax!",
    "Sunflower seeds contain vitamin B6, which helps your brain make 'feel-good' chemicals!",
    "Sesame seeds are one of the oldest oilseed crops known to humans!",
    "Your body needs carbohydrates for energy - they're like fuel for your body!",
    "Complex carbs like whole grains give you longer-lasting energy!",
    "Simple carbs like sugar give you quick energy that doesn't last long!",
    "Fiber is a type of carbohydrate that your body can't digest, but it's super important!",
    "Soluble fiber helps lower cholesterol and keeps your blood sugar steady!",
    "Insoluble fiber helps move food through your digestive system!",
    "Artichokes are one of the highest-fiber vegetables!",
    "Black beans have more fiber than most other beans!",
    "Popcorn is a whole grain and a good source of fiber!",
    "Whole grain pasta has more fiber than regular pasta!",
    "Barley was one of the first cultivated grains in history!",
    "Oats contain a special type of fiber called beta-glucan that's great for heart health!",
    "Buckwheat is not related to wheat - it's actually a fruit seed!",
    "Your muscles are made of protein - that's why you need it to grow strong!",
    "Protein helps repair tissues when you get a cut or bruise!",
    "Your hair and nails are mostly made of protein!",
    "Enzymes that help digest your food are made of protein!",
    "Some hormones that send messages in your body are made of protein!",
    "Antibodies that fight infections are made of protein!",
    "Complete proteins have all the essential amino acids your body needs!",
    "Incomplete proteins are missing some amino acids, but you can combine foods to get them all!",
    "Rice and beans together make a complete protein!",
    "Hummus and whole wheat pita make a complete protein!",
    "Peanut butter on whole wheat bread makes a complete protein!",
    "Your body can make some vitamins, but not all of them - that's why you need to eat them!",
    "Vitamin A is important for good vision, especially at night!",
    "Vitamin B helps convert food into energy!",
    "Vitamin C helps your body absorb iron from plant foods!",
    "Vitamin D helps your body absorb calcium!",
    "Vitamin E protects your cells from damage!",
    "Vitamin K helps your blood clot when you get a cut!",
    "Calcium is the most abundant mineral in your body!",
    "99% of the calcium in your body is in your bones and teeth!",
    "Iron carries oxygen in your blood from your lungs to the rest of your body!",
    "Magnesium is involved in over 300 chemical reactions in your body!",
    "Potassium helps balance fluids in your body and keeps your heart beating regularly!",
    "Zinc helps your immune system fight off germs!",
    "Iodine is needed for your thyroid gland to work properly!",
    "Selenium protects your cells from damage!",
    "Copper helps your body make red blood cells!",
    "Manganese helps your body form bones and connective tissue!",
    "Chromium helps insulin regulate blood sugar!",
    "Molybdenum helps break down proteins!",
    "Phosphorus works with calcium to build strong bones!",
    "Sodium helps maintain the right balance of fluids in your body, but too much isn't good!",
    "Chloride helps maintain proper blood volume and pressure!",
    "Sulfur helps detoxify your body!",
    "Fluoride helps prevent tooth decay!",
    "Cobalt is part of vitamin B12!",
    "Nickel may help your body use iron properly!",
    "Vanadium may help regulate blood sugar!",
    "Silicon helps form bones and connective tissue!",
    "Boron helps your body use calcium and magnesium!",
    "Arsenic is needed in tiny amounts, but too much is poisonous!",
    "Your body is about 60% water!",
    "Water regulates your body temperature through sweating!",
    "Water carries nutrients and oxygen to your cells!",
    "Water cushions your joints!",
    "Water protects your organs and tissues!",
    "You can survive weeks without food but only days without water!",
    "By the time you feel thirsty, you're already slightly dehydrated!",
    "Kids should drink about 6-8 cups of water a day!",
    "Exercise increases your need for water!",
    "Hot weather increases your need for water!",
    "Fruits and vegetables can contribute to your daily water needs!",
    "Soup, milk, and juice also count toward your fluid intake!",
    "Caffeine can make you lose water, so balance caffeinated drinks with water!",
    "Your body loses water through breathing, sweating, and going to the bathroom!",
    "Clear or pale yellow urine usually means you're well hydrated!",
    "Dark yellow urine usually means you need to drink more water!",
    "Exercise makes your heart stronger so it can pump more blood with each beat!",
    "Exercise makes your lungs stronger so you can take in more oxygen!",
    "Exercise helps your muscles get stronger and more efficient!",
    "Exercise helps your bones get denser and stronger!",
    "Exercise improves your balance and coordination!",
    "Exercise helps you maintain a healthy weight!",
    "Exercise reduces stress and anxiety!",
    "Exercise improves your mood!",
    "Exercise helps you sleep better!",
    "Exercise boosts your energy levels!",
    "Exercise improves your focus and concentration!",
    "Exercise strengthens your immune system!",
    "Different types of exercise have different benefits!",
    "Aerobic exercise like running is great for your heart and lungs!",
    "Strength training like push-ups builds strong muscles and bones!",
    "Flexibility exercises like stretching keep your muscles limber!",
    "Balance exercises like standing on one foot help prevent falls!",
    "Weight-bearing exercises like jumping help build strong bones!",
    "Non-weight-bearing exercises like swimming are easier on your joints!",
    "Exercise doesn't have to be boring - playing tag counts as exercise!",
    "Walking the dog counts as exercise!",
    "Dancing to your favorite music counts as exercise!",
    "Playing at the playground counts as exercise!",
    "Riding your bike counts as exercise!",
    "Jumping rope counts as exercise!",
    "Playing sports counts as exercise!",
    "Yoga combines strength, flexibility, and balance!",
    "Martial arts combine fitness with self-discipline!",
    "Gymnastics builds strength, flexibility, and coordination!",
    "Swimming is a full-body workout that's easy on joints!",
    "Basketball builds endurance and coordination!",
    "Soccer builds endurance and teamwork!",
    "Baseball builds hand-eye coordination!",
    "Tennis builds agility and coordination!",
    "Volleyball builds teamwork and coordination!",
    "Football builds strength and strategy!",
    "Hockey builds speed and coordination!",
    "Lacrosse builds endurance and coordination!",
    "Track and field builds speed, strength, and endurance!",
    "Cross country builds endurance and mental toughness!",
    "Wrestling builds strength and discipline!",
    "Cheerleading builds strength and teamwork!",
    "Skateboarding builds balance and coordination!",
    "Surfing builds balance and strength!",
    "Snowboarding builds balance and coordination!",
    "Skiing builds balance and leg strength!",
    "Ice skating builds balance and leg strength!",
    "Rollerblading builds balance and leg strength!",
    "Rock climbing builds strength and problem-solving skills!",
    "Parkour builds strength, agility, and creativity!",
    "Circus arts build strength, flexibility, and confidence!",
    "Dance builds coordination, rhythm, and creativity!",
    "Zumba combines dance and aerobics!",
    "Pilates builds core strength and flexibility!",
    "Tai chi combines movement and meditation!",
    "Karate builds discipline and self-defense skills!",
    "Judo builds balance and technique!",
    "Taekwondo builds flexibility and power!",
    "Kung fu builds strength and discipline!",
    "Capoeira combines martial arts, dance, and music!",
    "Fencing builds speed and strategy!",
    "Archery builds focus and upper body strength!",
    "Bowling builds hand-eye coordination!",
    "Golf builds concentration and patience!",
    "Horseback riding builds balance and core strength!",
    "Canoeing builds upper body strength!",
    "Kayaking builds upper body strength!",
    "Rowing builds full-body strength!",
    "Sailing builds coordination and weather knowledge!",
    "Stand-up paddleboarding builds balance and core strength!",
    "Snorkeling builds leg strength and teaches about marine life!",
    "Scuba diving teaches about marine life and builds calmness!",
    "Hiking builds endurance and connects you with nature!",
    "Backpacking builds endurance and survival skills!",
    "Camping teaches outdoor skills and connects you with nature!",
    "Fishing teaches patience and connects you with nature!",
    "Gardening builds strength and teaches about plants!",
    "Yard work builds strength and helps your family!",
    "House cleaning can be a workout!",
    "Walking up stairs is great exercise!",
    "Taking the dog for a walk is great exercise!",
    "Playing with siblings counts as exercise!",
    "Having a dance party counts as exercise!",
    "Doing cartwheels counts as exercise!",
    "Jumping on a trampoline counts as exercise!",
    "Playing hopscotch counts as exercise!",
    "Playing four square counts as exercise!",
    "Playing dodgeball counts as exercise!",
    "Playing kickball counts as exercise!",
    "Playing capture the flag counts as exercise!",
    "Playing hide and seek counts as exercise!",
    "Playing Simon says with movements counts as exercise!",
    "Doing an obstacle course counts as exercise!",
    "Racing your friends counts as exercise!",
    "Walking to school counts as exercise!",
    "Riding your bike to school counts as exercise!",
    "Scootering to school counts as exercise!",
    "Skateboarding to school counts as exercise!",
    "Rollerblading to school counts as exercise!",
    "Pushing a wheelchair counts as exercise!",
    "Wheelchair sports count as exercise!",
    "Adaptive sports count as exercise for everyone!",
    "Exercise should be fun, not a chore!",
    "Listening to music can make exercise more fun!",
    "Exercising with friends can make it more fun!",
    "Trying new activities keeps exercise interesting!",
    "Setting goals can motivate you to exercise!",
    "Tracking your progress can motivate you to exercise!",
    "Rewarding yourself for exercising can be motivating!",
    "Your body needs rest days to recover from exercise!",
    "Sleep is when your body repairs itself from exercise!",
    "Proper nutrition fuels your exercise!",
    "Carbohydrates are the main fuel for exercise!",
    "Protein helps repair muscles after exercise!",
    "Water is essential before, during, and after exercise!",
    "Electrolytes like sodium and potassium are lost in sweat!",
    "Sports drinks can replace electrolytes during long exercise!",
    "For most kids' activities, water is better than sports drinks!",
    "Warming up before exercise prevents injuries!",
    "Cooling down after exercise helps your body recover!",
    "Stretching after exercise when muscles are warm is best!",
    "Proper shoes prevent exercise injuries!",
    "Proper technique prevents exercise injuries!",
    "Listening to your body prevents exercise injuries!",
    "Pushing through pain can cause exercise injuries!",
    "RICE (Rest, Ice, Compression, Elevation) helps injuries heal!",
    "Everyone's body is different and needs different types of exercise!",
    "Exercise should make you feel good, not bad about yourself!",
    "All bodies can enjoy exercise in their own way!",
    "Exercise is for health and fun, not for changing how you look!",
    "Being active is more important than being athletic!",
    "Trying your best is more important than being the best!",
    "Having fun is the most important part of exercise!",
    "Eating disorders are serious mental health conditions!",
    "Eating disorders are not a choice - they're illnesses!",
    "Eating disorders can affect anyone, regardless of size, gender, or background!",
    "Eating disorders often involve unhealthy thoughts about food and body image!",
    "Anorexia nervosa involves restricting food intake!",
    "Bulimia nervosa involves binge eating followed by purging!",
    "Binge eating disorder involves eating large amounts without purging!",
    "ARFID involves avoiding certain foods due to texture or fear!",
    "Pica involves eating non-food items!",
    "Rumination disorder involves regurgitating and re-chewing food!",
    "Orthorexia involves an unhealthy obsession with 'healthy' eating!",
    "Eating disorders have the highest mortality rate of any mental illness!",
    "Eating disorders often coexist with other mental health conditions!",
    "Genetics can play a role in eating disorders!",
    "Societal pressure about appearance can contribute to eating disorders!",
    "Teasing about weight can contribute to eating disorders!",
    "Dieting can sometimes lead to eating disorders!",
    "Eating disorders often develop during teenage years!",
    "Boys can get eating disorders too!",
    "Athletes are at higher risk for eating disorders!",
    "Dancers are at higher risk for eating disorders!",
    "Models are at higher risk for eating disorders!",
    "Actors are at higher risk for eating disorders!",
    "People in certain sports like wrestling and gymnastics are at higher risk!",
    "Eating disorders can cause serious physical health problems!",
    "Eating disorders can damage the heart!",
    "Eating disorders can damage the digestive system!",
    "Eating disorders can damage the bones!",
    "Eating disorders can damage the teeth!",
    "Eating disorders can cause hair loss!",
    "Eating disorders can cause skin problems!",
    "Eating disorders can cause fertility problems!",
    "Eating disorders can stunt growth!",
    "Eating disorders can cause brain damage!",
    "Eating disorders can be fatal!",
    "Early treatment of eating disorders leads to better recovery!",
    "Eating disorders are treatable with professional help!",
    "Treatment often involves therapy!",
    "Treatment sometimes involves medication!",
    "Treatment often involves nutrition counseling!",
    "Treatment sometimes involves hospitalization!",
    "Family support is important in eating disorder recovery!",
    "Friends can support someone with an eating disorder by being kind and understanding!",
    "You should never comment on someone's weight or eating habits!",
    "You should never encourage someone to diet!",
    "You should never tease someone about their appearance!",
    "You should never compare your body to others' bodies!",
    "All bodies are good bodies!",
    "Health comes in all shapes and sizes!",
    "You can't tell if someone is healthy just by looking at them!",
    "Weight is not the best measure of health!",
    "The number on the scale doesn't define your worth!",
    "Your worth is not determined by your appearance!",
    "You are more than your body!",
    "Your character is more important than your appearance!",
    "Your talents are more important than your appearance!",
    "Your kindness is more important than your appearance!",
    "Your intelligence is more important than your appearance!",
    "Your creativity is more important than your appearance!",
    "Your sense of humor is more important than your appearance!",
    "Your friendships are more important than your appearance!",
    "Your family is more important than your appearance!",
    "Your hobbies are more important than your appearance!",
    "Your dreams are more important than your appearance!",
    "Your values are more important than your appearance!",
    "Media images are often edited and not realistic!",
    "Social media often shows only the best moments, not real life!",
    "Comparing yourself to others on social media can make you feel bad!",
    "Following body-positive accounts can help you feel better about yourself!",
    "Unfollowing accounts that make you feel bad about yourself is healthy!",
    "Taking breaks from social media can be good for mental health!",
    "Real beauty comes in all shapes, sizes, colors, and abilities!",
    "What makes you unique is what makes you beautiful!",
    "Scars, birthmarks, and differences make you uniquely you!",
    "Your body is amazing because it allows you to experience the world!",
    "Your body allows you to hug loved ones!",
    "Your body allows you to play!",
    "Your body allows you to learn!",
    "Your body allows you to create!",
    "Your body allows you to help others!",
    "Your body deserves kindness and respect!",
    "You should talk to your body like you would talk to a good friend!",
    "Negative self-talk can hurt your mental health!",
    "Positive self-talk can improve your mental health!",
    "Complimenting yourself can boost your self-esteem!",
    "Complimenting others can boost their self-esteem!",
    "Focus on what your body can DO, not just how it looks!",
    "Appreciate your body for getting you through each day!",
    "Intuitive eating means listening to your body's hunger signals!",
    "Intuitive eating means eating when you're hungry!",
    "Intuitive eating means stopping when you're full!",
    "Intuitive eating means eating what you're craving in moderation!",
    "Intuitive eating means not labeling foods as 'good' or 'bad'!",
    "All foods can fit in a healthy diet!",
    "Balance means eating different types of foods!",
    "Variety means eating different foods within each food group!",
    "Moderation means not having too much or too little of anything!",
    "Sometimes foods are treats to enjoy occasionally!",
    "Everyday foods are nutritious foods to eat regularly!",
    "Food is not just fuel - it's also pleasure, culture, and connection!",
    "Eating with family can be good for mental health!",
    "Eating without distractions helps you enjoy food more!",
    "Mindful eating means paying attention to your food while eating!",
    "Mindful eating helps you notice when you're full!",
    "Mindful eating helps you appreciate your food more!",
    "Cooking can be a fun way to learn about nutrition!",
    "Gardening can help you appreciate where food comes from!",
    "Trying new foods can be an adventure!",
    "Food from different cultures can be delicious and nutritious!",
    "Respecting others' food choices is important!",
    "Some people have food allergies that require avoiding certain foods!",
    "Some people have medical conditions that require special diets!",
    "Some people choose not to eat certain foods for religious reasons!",
    "Some people choose not to eat animal products for ethical reasons!",
    "Vegetarians don't eat meat but may eat eggs and dairy!",
    "Vegans don't eat any animal products!",
    "Pescatarians eat fish but not other meats!",
    "Flexitarians mostly eat plants but occasionally eat meat!",
    "All eating patterns can be healthy with proper planning!",
    "Breakfast literally means 'breaking the fast' from overnight!",
    "Your metabolism is how your body converts food into energy!",
    "Your basal metabolic rate is how many calories you burn at rest!",
    "Muscle burns more calories at rest than fat does!",
    "Building muscle through exercise can slightly increase metabolism!",
    "Eating small meals throughout the day can keep energy steady!",
    "Eating large meals can make you feel sleepy!",
    "Carbohydrates, protein, and fat are the three macronutrients!",
    "Vitamins and minerals are micronutrients!",
    "Phytonutrients are plant compounds with health benefits!",
    "Antioxidants protect your cells from damage!",
    "Free radicals are unstable molecules that can damage cells!",
    "Oxidative stress occurs when there are too many free radicals!",
    "Antioxidants neutralize free radicals!",
    "Berries are packed with antioxidants!",
    "Dark leafy greens are packed with antioxidants!",
    "Nuts and seeds are packed with antioxidants!",
    "Dark chocolate is packed with antioxidants!",
    "Green tea is packed with antioxidants!",
    "Spices like turmeric and cinnamon are packed with antioxidants!",
    "Herbs like oregano and rosemary are packed with antioxidants!",
    "Eating the rainbow ensures you get different antioxidants!",
    "Fermented foods like yogurt and sauerkraut contain probiotics!",
    "Probiotics are good bacteria for your gut!",
    "Prebiotics are fiber that feed probiotics!",
    "A healthy gut microbiome is important for overall health!",
    "Your gut and brain are connected through the gut-brain axis!",
    "A healthy gut can improve your mood!",
    "Processed foods often have fewer nutrients than whole foods!",
    "Ultra-processed foods are linked to poor health!",
    "Reading nutrition labels helps you make informed choices!",
    "Ingredients are listed from most to least by weight!",
    "Serving size is important when reading nutrition labels!",
    "% Daily Value shows how much a nutrient contributes to your daily needs!",
];

var EXERCISE_CHALLENGES = EXERCISE_CHALLENGES || [
   "Do 5 jumping jacks! Ready? Go!",
    "Stretch up high like you're picking an apple from a tree!",
    "Balance on one foot for 10 seconds!",
    "Take 3 deep breaths to relax your mind!",
    "Do 4 arm circles forward and backward!",
    "Touch your toes 5 times!",
    "Do 3 squats like you're sitting in a chair!",
    "March in place for 15 seconds!",
    "Reach for the sky and hold for 5 seconds!",
    "Do 2 lunges on each leg!",
    "Spin around 3 times carefully!",
    "Pretend to jump rope 10 times!",
    "Do the windmill stretch - touch right hand to left foot!",
    "Take a walk around the room!",
    "Do 5 knee lifts while marching!"
];

var WIN_MESSAGES = WIN_MESSAGES || [
    "Remember: A balanced diet is key to a healthy life!",
    "Keep eating colorful fruits and vegetables every day!",
    "Don't forget to drink plenty of water!",
    "Exercise and good nutrition work together for health!",
    "Try new healthy foods - you might discover a new favorite!",
    "Breakfast is the most important meal of the day!",
    "Listen to your body - eat when you're hungry, stop when you're full!",
    "Healthy eating helps you grow strong and smart!",
    "Make half your plate fruits and vegetables!",
    "Choose whole grains instead of refined grains!",
    "Be active for at least 60 minutes every day!",
    "Limit screen time and get moving instead!",
    "Eat foods from all food groups every day!",
    "Healthy snacks give you energy between meals!",
    "You are what you eat - choose wisely!"
];

console.log("Nutrition Warfare data loaded successfully!");
console.log("Questions:", QUESTIONS.length);
console.log("Facts:", FACTS.length);
console.log("Exercises:", EXERCISE_CHALLENGES.length);
console.log("Win messages:", WIN_MESSAGES.length);